version: "3.9"
services:
  flight_tracker_dev:
    container_name: flight_tracker_dev
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3003:3000"
    volumes:
      - /app/node_modules
      - .:/app